### ISSUE TITLE
Failed to write frame to ffmpeg: Broken pipe (os error 32)

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#228] opened 2024-08-26 10:10 UTC
>ERROR screenpipe_server::video] Failed to write frame to ffmpeg: Broken pipe (os error 32)

this is a new error, did not exist last week

gotta look at what changed but this error is nondeterminisitc (e.g. sometime just restart and it works) and affects only the screen video encoding

/bounty 50

**Comment by tmahmood** [comment] 2024-08-28 09:59
Interested about this. Can you describe how to reproduce this error? When this error occurs?

**Comment by louis030195** [comment] 2024-08-28 12:33
i have no idea

does not happen frequently, seems random

**Comment by tmahmood** [comment] 2024-08-28 13:28
Any debug log? Does this happen to fresh install? Is it fatal? I'm seeing many errors about missing files, but have not seen this one.

**Comment by louis030195** [comment] 2024-08-28 16:05
@tmahmood what do you mean missing files?

did not see anyone complaining about this for 3-4 days so i think you might just look at solving other issues and maybe it will come up

**Comment by booti386** [comment] 2024-08-28 18:05
Which operating system? It looks like ffmpeg closes its input stream (crashes maybe?) before receiving all the data.

**Comment by louis030195** [comment] 2024-08-29 08:03
@booti386 saw this on linux (some user) and on my mac once

**Comment by louis030195** [comment] 2024-09-05 18:37
<img width="686" alt="image" src="https://github.com/user-attachments/assets/4032b020-1c86-44d3-a881-fa4e0d2d94aa">

**Comment by MinisculeGirraffe** [comment] 2024-09-05 19:32
There's no practical way to debug this because you're not pinning a known ffmpeg version with the application.

For some reason, ffmpeg is closing it's input stream, so that log is being generated. 

I could add retry logic so when the input stream is closed it re-creates a new process. But that doesn't exactly solve the root issue here of "It's going to do weird stuff because platform/feature flag/version differences".

**Comment by louis030195** [comment] 2024-09-05 20:45
@MinisculeGirraffe probably solving this https://github.com/mediar-ai/screenpipe/issues/194 would be a more long term investment if you want to give a try

**Closed** 2024-10-21 17:51 UTC
Labels: 💎 Bounty

**Comment by heo001997** [comment] 2024-12-17 03:14
@louis030195 this is the exact way to fix the error on my macos (fresh install DEC 17)

```
brew reinstall x265
```

And that `Failed to write frame to ffmpeg: Broken pipe (os error 32)` will be completely gone, good luck!

**Comment by jesse-c** [comment] 2025-01-01 22:07
> @louis030195 this is the exact way to fix the error on my macos (fresh install DEC 17)
> 
> ```
> brew reinstall x265
> ```
> 
> And that `Failed to write frame to ffmpeg: Broken pipe (os error 32)` will be completely gone, good luck!

This also fixed it for me on macOS.

**Comment by storm1729** [comment] 2025-05-28 14:11
> brew reinstall x265

Didn't work for me, but `brew reinstall ffmpeg` did. Also on macos
